name: CI # integration to develop branch
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
      - develop
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.34.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
        RELEASE_BRANCHES: main,develop
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PW }}
    - name: docker pull base image
      run: docker pull notadockerhub/ci_test:base
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PW }}
        repository: notadockerhub/netspresso_server
        dockerfile: dockerfiles/dockerfile.release
        tag_with_ref: true
        tags: latest-release, ${{ steps.tag_version.outputs.new_tag }}